// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'Mdi:controllerXbox': typeof import('virtual:vite-icons/mdi/controller-xbox')['default']
  }
}

export { }
