// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Translate: typeof import('./src/components/Translate.vue')['default']
    'Mdi:emoticonCool': typeof import('virtual:vite-icons/mdi/emoticon-cool')['default']
    'Mdi:translate': typeof import('virtual:vite-icons/mdi/translate')['default']
  }
}

export { }
